"""Hand-authored seed benchmark tasks (original, CC BY 4.0).

These are the ~original tasks of SPEC §4; SO/tldr/GitHub-derived items get added by
the curation tool with attribution. Each task's expected_output is filled in by
executing reference_program with the pinned jq (see build_seed.py) so it is ground truth.
"""

SEED = [
    dict(id="seed-001", request="list the names of all users",
         input=[{"name": "Ada", "age": 36}, {"name": "Linus", "age": 54}],
         reference_program="map(.name)", tags=["pluck"], difficulty=1),
    dict(id="seed-002", request="how many orders are there",
         input=[{"id": 1}, {"id": 2}, {"id": 3}],
         reference_program="length", tags=["count"], difficulty=1),
    dict(id="seed-003", request="the email of the first user",
         input=[{"name": "Ada", "email": "ada@x.io"}, {"name": "Linus", "email": "l@x.io"}],
         reference_program=".[0].email", tags=["index"], difficulty=1),
    dict(id="seed-004", request="orders with status paid",
         input=[{"id": 1, "status": "paid"}, {"id": 2, "status": "pending"},
                {"id": 3, "status": "paid"}],
         reference_program="map(select(.status == \"paid\"))", tags=["filter"], difficulty=1),
    dict(id="seed-005", request="total of all amounts",
         input=[{"amount": 10}, {"amount": 25}, {"amount": 5}],
         reference_program="map(.amount) | add", tags=["sum"], difficulty=1),
    dict(id="seed-006", request="names of users older than 40",
         input=[{"name": "Ada", "age": 36}, {"name": "Linus", "age": 54},
                {"name": "Grace", "age": 71}],
         reference_program="map(select(.age > 40) | .name)", tags=["filter", "pluck"], difficulty=2),
    dict(id="seed-007", request="the distinct set of statuses",
         input=[{"status": "paid"}, {"status": "pending"}, {"status": "paid"}],
         reference_program="[.[].status] | unique", tags=["unique"], difficulty=2,
         order_insensitive=True),
    dict(id="seed-008", request="count how many builds failed",
         input=[{"result": "success"}, {"result": "failure"}, {"result": "failure"}],
         reference_program="[.[] | select(.result == \"failure\")] | length",
         tags=["count", "filter"], difficulty=2),
    dict(id="seed-009", request="average age of the users",
         input=[{"age": 30}, {"age": 40}, {"age": 50}],
         reference_program="(map(.age) | add) / length", tags=["sum", "arith"], difficulty=3),
    dict(id="seed-010", request="sort the products by price ascending and give their names",
         input=[{"name": "b", "price": 9}, {"name": "a", "price": 3},
                {"name": "c", "price": 20}],
         reference_program="sort_by(.price) | map(.name)", tags=["sort", "pluck"], difficulty=2),
    dict(id="seed-011", request="total revenue per customer",
         input=[{"customer": "A", "total": 10}, {"customer": "B", "total": 5},
                {"customer": "A", "total": 7}],
         reference_program="group_by(.customer) | map({customer: .[0].customer, total: (map(.total) | add)})",
         tags=["group_by", "sum"], difficulty=3, order_insensitive=True),
    dict(id="seed-012", request="the user with the most followers",
         input=[{"name": "A", "followers": 10}, {"name": "B", "followers": 99},
                {"name": "C", "followers": 5}],
         reference_program="max_by(.followers)", tags=["max_by"], difficulty=2),
    dict(id="seed-013", request="just the ids as a comma separated line",
         input=[{"id": 1}, {"id": 2}, {"id": 3}],
         reference_program="[.[].id] | @csv", tags=["format"], difficulty=3),
    dict(id="seed-014", request="all the keys of the config object",
         input={"host": "localhost", "port": 8080, "tls": True},
         reference_program="keys", tags=["keys"], difficulty=1, order_insensitive=True),
    dict(id="seed-015", request="does any order have quantity over 100",
         input=[{"quantity": 3}, {"quantity": 150}, {"quantity": 1}],
         reference_program="any(.quantity > 100)", tags=["any"], difficulty=3),
    dict(id="seed-016", request="the second and third items",
         input=[10, 20, 30, 40, 50],
         reference_program=".[1:3]", tags=["slice"], difficulty=2),
    dict(id="seed-017", request="rename the field 'qty' to 'quantity' in each row",
         input=[{"qty": 2, "sku": "x"}, {"qty": 5, "sku": "y"}],
         reference_program="map({quantity: .qty, sku: .sku})", tags=["reshape"], difficulty=3),
    dict(id="seed-018", request="count of records per status",
         input=[{"status": "paid"}, {"status": "paid"}, {"status": "pending"}],
         reference_program="group_by(.status) | map({status: .[0].status, count: length})",
         tags=["group_by", "count"], difficulty=3, order_insensitive=True),
    dict(id="seed-019", request="the name of every repo, uppercased",
         input=[{"name": "datasette"}, {"name": "jq"}],
         reference_program="map(.name | ascii_upcase)", tags=["pluck", "string"], difficulty=2),
    dict(id="seed-020", request="items where the tags array contains \"urgent\"",
         input=[{"id": 1, "tags": ["a", "urgent"]}, {"id": 2, "tags": ["b"]}],
         reference_program="map(select(.tags | index(\"urgent\")))",
         tags=["filter", "array"], difficulty=4),
    dict(id="seed-021", request="flatten the nested lists into one array",
         input=[[1, 2], [3], [4, 5]],
         reference_program="flatten", tags=["flatten"], difficulty=2),
    dict(id="seed-022", request="sum of amount only for pending transactions",
         input=[{"amount": 10, "pending": True}, {"amount": 5, "pending": False},
                {"amount": 8, "pending": True}],
         reference_program="[.[] | select(.pending) | .amount] | add",
         tags=["filter", "sum"], difficulty=3),
    dict(id="seed-023", request="the price field, defaulting to 0 when it is missing",
         input=[{"price": 12}, {"sku": "x"}, {"price": 4}],
         reference_program="map(.price // 0)", tags=["alternative"], difficulty=3),
    dict(id="seed-024", request="pretty list of 'name: age' strings",
         input=[{"name": "Ada", "age": 36}, {"name": "Linus", "age": 54}],
         reference_program="map(\"\\(.name): \\(.age)\")", tags=["string", "interp"], difficulty=4),
    dict(id="seed-025", request="the top 2 repos by stars, names only",
         input=[{"name": "a", "stars": 5}, {"name": "b", "stars": 99},
                {"name": "c", "stars": 40}],
         reference_program="sort_by(-.stars) | .[0:2] | map(.name)",
         tags=["sort", "slice", "pluck"], difficulty=4),
]
