"""Extended hand-authored benchmark tasks (original, CC BY 4.0).

Second wave of hand-authored tasks (seed-026+) broadening feature coverage beyond
the 25 core tasks: nested access, reshaping, string/regex, arithmetic, group_by
aggregation, entries transforms, reduce/first, and boolean composition. Many use jq
builtins that appear rarely or never in the synthetic training grammar, so they probe
compositional generalization rather than memorization. Every expected_output is filled
by executing reference_program with the pinned jq (see build_seed.py).
"""

SEED_EXT = [
    dict(id="seed-026", request="the name of each event's user",
         input=[{"user": {"name": "Ada"}}, {"user": {"name": "Linus"}}],
         reference_program="map(.user.name)", tags=["pluck", "nested"], difficulty=2),
    dict(id="seed-027", request="list the config as key/value pairs",
         input={"host": "localhost", "port": 8080},
         reference_program="to_entries", tags=["entries", "object"], difficulty=3),
    dict(id="seed-028", request="split the path into its segments",
         input="/usr/local/bin",
         reference_program="split(\"/\")", tags=["string", "split"], difficulty=2),
    dict(id="seed-029", request="join the tags with a comma",
         input=["red", "green", "blue"],
         reference_program="join(\",\")", tags=["string", "join"], difficulty=2),
    dict(id="seed-030", request="the users, deduplicated by email",
         input=[{"email": "a@x.io", "n": 1}, {"email": "a@x.io", "n": 2},
                {"email": "b@x.io", "n": 3}],
         reference_program="unique_by(.email)", tags=["unique_by"], difficulty=3,
         order_insensitive=True),
    dict(id="seed-031", request="the cheapest product",
         input=[{"name": "a", "price": 9}, {"name": "b", "price": 3}],
         reference_program="min_by(.price)", tags=["min_by"], difficulty=2),
    dict(id="seed-032", request="the total quantity across all line items",
         input=[{"qty": 2}, {"qty": 5}, {"qty": 1}],
         reference_program="reduce .[].qty as $q (0; . + $q)", tags=["reduce", "sum"],
         difficulty=4),
    dict(id="seed-033", request="the names that start with 'A'",
         input=[{"name": "Ada"}, {"name": "Bob"}, {"name": "Alan"}],
         reference_program="map(select(.name | startswith(\"A\")) | .name)",
         tags=["filter", "string"], difficulty=3),
    dict(id="seed-034", request="log lines containing the word error",
         input=[{"msg": "disk error"}, {"msg": "ok"}, {"msg": "error 500"}],
         reference_program="map(select(.msg | contains(\"error\")))",
         tags=["filter", "string"], difficulty=3),
    dict(id="seed-035", request="records that have a discount field",
         input=[{"id": 1, "discount": 5}, {"id": 2}, {"id": 3, "discount": 0}],
         reference_program="map(select(has(\"discount\")))", tags=["filter", "has"],
         difficulty=3),
    dict(id="seed-036", request="remove the password field from each user",
         input=[{"user": "a", "password": "x"}, {"user": "b", "password": "y"}],
         reference_program="map(del(.password))", tags=["del", "reshape"], difficulty=3),
    dict(id="seed-037", request="combine all the objects into one",
         input=[{"a": 1}, {"b": 2}, {"c": 3}],
         reference_program="add", tags=["add", "object"], difficulty=2,
         order_insensitive=True),
    dict(id="seed-038", request="flatten one level only",
         input=[[1, [2]], [3]],
         reference_program="flatten(1)", tags=["flatten"], difficulty=3),
    dict(id="seed-039", request="the position of 'blue' in the list",
         input=["red", "green", "blue"],
         reference_program="index(\"blue\")", tags=["index"], difficulty=2),
    dict(id="seed-040", request="the last event",
         input=[{"t": 1}, {"t": 2}, {"t": 3}],
         reference_program="last", tags=["index"], difficulty=1),
    dict(id="seed-041", request="turn the list of key/value pairs into an object",
         input=[{"key": "a", "value": 1}, {"key": "b", "value": 2}],
         reference_program="from_entries", tags=["entries", "object"], difficulty=4,
         order_insensitive=True),
    dict(id="seed-042", request="each title with spaces replaced by underscores",
         input=[{"title": "hello world"}, {"title": "a b c"}],
         reference_program="map(.title | gsub(\" \"; \"_\"))",
         tags=["string", "regex"], difficulty=4),
    dict(id="seed-043", request="lowercase every tag",
         input=["RED", "Green", "BLUE"],
         reference_program="map(ascii_downcase)", tags=["string"], difficulty=2),
    dict(id="seed-044", request="round each score to the nearest integer",
         input=[1.2, 2.7, 3.5],
         reference_program="map(round)", tags=["number"], difficulty=2),
    dict(id="seed-045", request="each price with 8 percent tax added",
         input=[{"price": 100}, {"price": 50}],
         reference_program="map(.price * 1.08)", tags=["arith"], difficulty=3),
    dict(id="seed-046", request="orders that are paid and over 100",
         input=[{"status": "paid", "total": 150}, {"status": "paid", "total": 20},
                {"status": "pending", "total": 300}],
         reference_program="map(select(.status == \"paid\" and .total > 100))",
         tags=["filter", "boolean"], difficulty=3),
    dict(id="seed-047", request="tasks that are urgent or overdue",
         input=[{"urgent": True, "overdue": False}, {"urgent": False, "overdue": True},
                {"urgent": False, "overdue": False}],
         reference_program="map(select(.urgent or .overdue))",
         tags=["filter", "boolean"], difficulty=3),
    dict(id="seed-048", request="double every value in the object",
         input={"a": 1, "b": 2, "c": 3},
         reference_program="map_values(. * 2)", tags=["object"], difficulty=3,
         order_insensitive=True),
    dict(id="seed-049", request="the number of fields in the object",
         input={"a": 1, "b": 2, "c": 3},
         reference_program="length", tags=["count", "object"], difficulty=1),
    dict(id="seed-050", request="all the values in the settings object",
         input={"width": 800, "height": 600},
         reference_program="[.[]]", tags=["object"], difficulty=2,
         order_insensitive=True),
    dict(id="seed-051", request="the highest temperature recorded",
         input=[{"temp": 20}, {"temp": 31}, {"temp": 25}],
         reference_program="map(.temp) | max", tags=["max"], difficulty=2),
    dict(id="seed-052", request="the lowest price",
         input=[9, 3, 20],
         reference_program="min", tags=["min"], difficulty=1),
    dict(id="seed-053", request="the sum of the list",
         input=[3, 5, 8],
         reference_program="add", tags=["sum"], difficulty=1),
    dict(id="seed-054", request="sort the numbers",
         input=[3, 1, 2],
         reference_program="sort", tags=["sort"], difficulty=1),
    dict(id="seed-055", request="the list in reverse order",
         input=[1, 2, 3],
         reference_program="reverse", tags=["reverse"], difficulty=1),
    dict(id="seed-056", request="the length of each word",
         input=["cat", "tiger", "ox"],
         reference_program="map(length)", tags=["string"], difficulty=2),
    dict(id="seed-057", request="emails that contain an @",
         input=[{"email": "a@x.io"}, {"email": "bad"}, {"email": "c@y.com"}],
         reference_program="map(select(.email | test(\"@\")))",
         tags=["filter", "regex"], difficulty=3),
    dict(id="seed-058", request="strip the leading 'v' from each version",
         input=["v1.2", "v3.0", "v10"],
         reference_program="map(ltrimstr(\"v\"))", tags=["string"], difficulty=3),
    dict(id="seed-059", request="the python files only",
         input=["a.py", "b.js", "c.py"],
         reference_program="map(select(endswith(\".py\")))", tags=["filter", "string"],
         difficulty=3),
    dict(id="seed-060", request="convert the string amounts to numbers and sum them",
         input=["10", "5", "8"],
         reference_program="map(tonumber) | add", tags=["number", "cast"], difficulty=3),
    dict(id="seed-061", request="the first failed job",
         input=[{"id": 1, "ok": True}, {"id": 2, "ok": False}, {"id": 3, "ok": False}],
         reference_program="first(.[] | select(.ok | not))", tags=["filter", "first"],
         difficulty=4),
    dict(id="seed-062", request="users who are not active",
         input=[{"n": "a", "active": True}, {"n": "b", "active": False}],
         reference_program="map(select(.active | not))", tags=["filter", "boolean"],
         difficulty=2),
    dict(id="seed-063", request="how many items are in each order",
         input=[{"id": 1, "items": [1, 2, 3]}, {"id": 2, "items": [1]}],
         reference_program="map(.items | length)", tags=["count", "array"], difficulty=2),
    dict(id="seed-064", request="total price, treating missing prices as zero",
         input=[{"price": 10}, {"x": 1}, {"price": 5}],
         reference_program="map(.price // 0) | add", tags=["alternative", "sum"],
         difficulty=3),
    dict(id="seed-065", request="temperatures between 20 and 30 inclusive",
         input=[{"t": 15}, {"t": 25}, {"t": 35}],
         reference_program="map(select(.t >= 20 and .t <= 30))", tags=["filter"],
         difficulty=3),
    dict(id="seed-066", request="just id and name for each user",
         input=[{"id": 1, "name": "a", "secret": "z"}, {"id": 2, "name": "b", "secret": "y"}],
         reference_program="map({id, name})", tags=["reshape"], difficulty=3),
    dict(id="seed-067", request="how many distinct statuses are there",
         input=[{"s": "a"}, {"s": "a"}, {"s": "b"}],
         reference_program="[.[].s] | unique | length", tags=["unique", "count"],
         difficulty=3),
    dict(id="seed-068", request="the name of the most expensive product",
         input=[{"name": "a", "price": 9}, {"name": "b", "price": 30}],
         reference_program="max_by(.price) | .name", tags=["max_by", "pluck"], difficulty=3),
    dict(id="seed-069", request="the average score per team",
         input=[{"team": "A", "score": 10}, {"team": "A", "score": 20},
                {"team": "B", "score": 5}],
         reference_program="group_by(.team) | map({team: .[0].team, avg: ((map(.score) | add) / length)})",
         tags=["group_by", "arith"], difficulty=5, order_insensitive=True),
    dict(id="seed-070", request="the names of settings that are enabled",
         input={"dark": True, "beta": False, "sound": True},
         reference_program="to_entries | map(select(.value) | .key)",
         tags=["entries", "filter"], difficulty=4, order_insensitive=True),
    dict(id="seed-071", request="increment every product's stock by 1",
         input=[{"stock": 3}, {"stock": 0}],
         reference_program="map(.stock += 1)", tags=["update"], difficulty=3),
    dict(id="seed-072", request="the three largest numbers, descending",
         input=[5, 1, 9, 3, 7, 2],
         reference_program="sort | reverse | .[0:3]", tags=["sort", "slice"], difficulty=4),
    dict(id="seed-073", request="group the words by their first letter",
         input=["apple", "avocado", "banana", "cherry"],
         reference_program="group_by(.[0:1])", tags=["group_by", "string"], difficulty=5,
         order_insensitive=True),
    dict(id="seed-074", request="the ids of orders over 100, as a JSON array",
         input=[{"id": 1, "total": 150}, {"id": 2, "total": 50}, {"id": 3, "total": 200}],
         reference_program="[.[] | select(.total > 100) | .id]", tags=["filter", "pluck"],
         difficulty=3),
    dict(id="seed-075", request="each user's full name from first and last",
         input=[{"first": "Ada", "last": "L"}, {"first": "Linus", "last": "T"}],
         reference_program="map(.first + \" \" + .last)", tags=["string", "concat"],
         difficulty=3),
]
