"""Harder, compositional benchmark tasks (original, CC BY 4.0).

Third wave (seed-076+): multi-step programs — group-and-aggregate, top-N-per-group,
above-average filters, nested any/all, entries round-trips, string pipelines. These are
the realistic jq one-liners people actually struggle to write, and the ones a
grammar-specialized small model is least likely to have seen. expected_output is filled
by executing reference_program with the pinned jq (see build_seed.py).
"""

SEED_HARD = [
    dict(id="seed-076", request="the top 3 customers by total spend, as {customer, spend}",
         input=[{"customer": "A", "total": 40}, {"customer": "B", "total": 10},
                {"customer": "A", "total": 25}, {"customer": "C", "total": 90},
                {"customer": "D", "total": 5}],
         reference_program="group_by(.customer) | map({customer: .[0].customer, spend: (map(.total) | add)}) | sort_by(-.spend) | .[0:3]",
         tags=["group_by", "sum", "sort", "slice"], difficulty=6),
    dict(id="seed-077", request="count of orders per status, keeping only statuses with more than one",
         input=[{"status": "paid"}, {"status": "paid"}, {"status": "pending"},
                {"status": "refunded"}, {"status": "refunded"}, {"status": "refunded"}],
         reference_program="group_by(.status) | map({status: .[0].status, n: length}) | map(select(.n > 1))",
         tags=["group_by", "count", "filter"], difficulty=6, order_insensitive=True),
    dict(id="seed-078", request="names of users who have the admin role",
         input=[{"name": "a", "roles": ["user", "admin"]}, {"name": "b", "roles": ["user"]},
                {"name": "c", "roles": ["admin"]}],
         reference_program="map(select(.roles | index(\"admin\")) | .name)",
         tags=["filter", "array", "pluck"], difficulty=5),
    dict(id="seed-079", request="total price of in-stock items only",
         input=[{"price": 10, "stock": 5}, {"price": 20, "stock": 0}, {"price": 5, "stock": 2}],
         reference_program="[.[] | select(.stock > 0) | .price] | add",
         tags=["filter", "sum"], difficulty=4),
    dict(id="seed-080", request="the average of the values in the object",
         input={"a": 10, "b": 20, "c": 30},
         reference_program="[.[]] | add / length", tags=["object", "arith"], difficulty=5),
    dict(id="seed-081", request="group events by type and list the ids in each group",
         input=[{"type": "click", "id": 1}, {"type": "view", "id": 2}, {"type": "click", "id": 3}],
         reference_program="group_by(.type) | map({type: .[0].type, ids: map(.id)})",
         tags=["group_by", "reshape"], difficulty=6, order_insensitive=True),
    dict(id="seed-082", request="the second highest score",
         input=[{"score": 10}, {"score": 50}, {"score": 30}],
         reference_program="[.[].score] | sort | reverse | .[1]",
         tags=["sort", "index"], difficulty=5),
    dict(id="seed-083", request="the percentage of orders that are paid",
         input=[{"status": "paid"}, {"status": "pending"}, {"status": "paid"},
                {"status": "refunded"}],
         reference_program="(map(select(.status == \"paid\")) | length) * 100 / length",
         tags=["filter", "arith"], difficulty=6),
    dict(id="seed-084", request="the emails, sorted by user name",
         input=[{"name": "Zed", "email": "z@x"}, {"name": "Ada", "email": "a@x"}],
         reference_program="sort_by(.name) | map(.email)", tags=["sort", "pluck"], difficulty=4),
    dict(id="seed-085", request="each record as {id, name} where name joins first and last",
         input=[{"id": 1, "first": "Ada", "last": "L"}, {"id": 2, "first": "Bo", "last": "T"}],
         reference_program="map({id, name: (.first + \" \" + .last)})",
         tags=["reshape", "string"], difficulty=5),
    dict(id="seed-086", request="how many times each tag appears across all posts",
         input=[{"tags": ["a", "b"]}, {"tags": ["a"]}, {"tags": ["b", "c"]}],
         reference_program="[.[].tags[]] | group_by(.) | map({tag: .[0], n: length})",
         tags=["flatten", "group_by", "count"], difficulty=6, order_insensitive=True),
    dict(id="seed-087", request="records where every score is above 50",
         input=[{"scores": [60, 70]}, {"scores": [40, 90]}, {"scores": [55, 80]}],
         reference_program="map(select(.scores | all(. > 50)))",
         tags=["filter", "array", "all"], difficulty=6),
    dict(id="seed-088", request="the domain of each email (the part after the @)",
         input=[{"email": "a@x.io"}, {"email": "b@y.com"}],
         reference_program="map(.email | split(\"@\")[1])",
         tags=["string", "split"], difficulty=5),
    dict(id="seed-089", request="the orders whose total is above the average total",
         input=[{"total": 10}, {"total": 20}, {"total": 60}],
         reference_program="(map(.total) | add / length) as $avg | map(select(.total > $avg))",
         tags=["variable", "arith", "filter"], difficulty=7),
    dict(id="seed-090", request="the key with the highest value",
         input={"a": 3, "b": 9, "c": 5},
         reference_program="to_entries | max_by(.value) | .key",
         tags=["entries", "max_by"], difficulty=6),
    dict(id="seed-091", request="all distinct tags across posts",
         input=[{"tags": ["b", "a"]}, {"tags": ["a", "c"]}],
         reference_program="[.[].tags[]] | unique",
         tags=["flatten", "unique"], difficulty=5, order_insensitive=True),
    dict(id="seed-092", request="the number of words in each sentence",
         input=["hello world", "one two three"],
         reference_program="map(split(\" \") | length)",
         tags=["string", "split", "count"], difficulty=4),
    dict(id="seed-093", request="the ids of the two cheapest products",
         input=[{"id": 1, "price": 9}, {"id": 2, "price": 3}, {"id": 3, "price": 5}],
         reference_program="sort_by(.price) | .[0:2] | map(.id)",
         tags=["sort", "slice", "pluck"], difficulty=5),
    dict(id="seed-094", request="total quantity per sku as an object",
         input=[{"sku": "a", "qty": 2}, {"sku": "b", "qty": 1}, {"sku": "a", "qty": 3}],
         reference_program="group_by(.sku) | map({key: .[0].sku, value: (map(.qty) | add)}) | from_entries",
         tags=["group_by", "entries", "sum"], difficulty=7, order_insensitive=True),
    dict(id="seed-095", request="users whose name contains a space",
         input=[{"name": "Ada L"}, {"name": "Bob"}, {"name": "C D"}],
         reference_program="map(select(.name | test(\" \")))",
         tags=["filter", "regex"], difficulty=5),
    dict(id="seed-096", request="the minimum and maximum price as {min, max}",
         input=[{"price": 5}, {"price": 20}, {"price": 9}],
         reference_program="{min: (map(.price) | min), max: (map(.price) | max)}",
         tags=["object", "min", "max"], difficulty=5),
    dict(id="seed-097", request="each string reversed",
         input=["abc", "de"],
         reference_program="map(explode | reverse | implode)",
         tags=["string"], difficulty=6),
    dict(id="seed-098", request="only the even numbers",
         input=[1, 2, 3, 4, 5, 6],
         reference_program="map(select(. % 2 == 0))",
         tags=["filter", "arith"], difficulty=4),
    dict(id="seed-099", request="the sum of the squares of the numbers",
         input=[1, 2, 3],
         reference_program="map(. * .) | add", tags=["arith", "sum"], difficulty=4),
    dict(id="seed-100", request="each order tagged with whether it is expensive (over 100)",
         input=[{"id": 1, "total": 150}, {"id": 2, "total": 50}],
         reference_program="map({id, expensive: (.total > 100)})",
         tags=["reshape", "boolean"], difficulty=4),
]
